# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoMet
                                 A QGIS plugin
 The GeoMet plugin is a powerful and user-friendly extension for QGIS, designed to seamlessly integrate real-time weather data with your geospatial projects.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-17
        copyright            : (C) 2023 by Ahmed Abdelkarim
        email                : a.abdelkarim9696@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoMet class from file GeoMet.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_met import GeoMet
    return GeoMet(iface)
